```{r}
library(ggplot2)
library(glue)
library(tidyverse)

```


```{r}
cc_root <- "/projects/p31666/zzhang/doublet-bchmk/data/cellchat_output"

```

```{r}
all_cc_dirs <- list.dirs(cc_root, full.names = T, recursive = F)
plot_df <- list()

for(cur_cc_dir in all_cc_dirs){
  all_cc_files <- list.files(cur_cc_dir, full.names = T)
  
  ten_file <- grep("ten", all_cc_files, value = TRUE)
  twenty_file <- grep("twenty", all_cc_files, value = TRUE)
  control_file <- grep("control", all_cc_files, value = TRUE)
  forty_file <- grep("forty", all_cc_files, value = TRUE)
  
  cur_dataset <- basename(cur_cc_dir)
  
  doublet_pct <- "0%"
  control_cc_df <- read.csv(control_file)
  control_cc_df[["complete_int_name"]] <- glue("{control_cc_df$source}__{control_cc_df$target}__{control_cc_df$interaction_name}")
  control_cc <- control_cc_df[["complete_int_name"]]
  if(!duplicated(control_cc)|>all() == FALSE){
    print("STOP")
    break
  }
  
  ten_cc_df <- read.csv(ten_file)
  ten_cc_df[["complete_int_name"]] <- glue("{ten_cc_df$source}__{ten_cc_df$target}__{ten_cc_df$interaction_name}")
  ten_cc <- ten_cc_df[["complete_int_name"]]
  if(!duplicated(ten_cc)|>all() == FALSE){
    print("STOP")
    break
  }
  
  
  twenty_cc_df <- read.csv(twenty_file)
  twenty_cc_df[["complete_int_name"]] <- glue("{twenty_cc_df$source}__{twenty_cc_df$target}__{twenty_cc_df$interaction_name}")
  twenty_cc <- twenty_cc_df[["complete_int_name"]]
  if(!duplicated(twenty_cc)|>all() == FALSE){
    print("STOP")
    break
  }
  
  forty_cc_df <- read.csv(forty_file)
  forty_cc_df[["complete_int_name"]] <- glue("{forty_cc_df$source}__{forty_cc_df$target}__{forty_cc_df$interaction_name}")
  forty_cc <- forty_cc_df[["complete_int_name"]]
  if(!duplicated(forty_cc)|>all() == FALSE){
    print("STOP")
    break
  }
  
  
  # for ten dbl 
  # True Positives: Elements in both
  TP <- length(intersect(control_cc, ten_cc))

  # False Positives: Elements in predictions but not in ground truth
  FP <- length(setdiff(ten_cc, control_cc))  
  FN <- length(setdiff(control_cc, ten_cc)) 
  precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
  recall <- TP / (TP + FN )  # recall: TP out of all elements
  cur_ten_out <- list(
    "dbl_pct" = "10%",
    "dataset" = cur_dataset,
    "precision" = precision,
    "recall" = recall
  )
  plot_df[[ten_file]] <- cur_ten_out
  
  # for twenty dbl 
  # True Positives: Elements in both
  TP <- length(intersect(control_cc, twenty_cc))

  # False Positives: Elements in predictions but not in ground truth
  FP <- length(setdiff(twenty_cc, control_cc))  
  FN <- length(setdiff(control_cc, twenty_cc)) 
  precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
  recall <- TP / (TP + FN )  # recall: TP out of all elements
  cur_twenty_out <- list(
    "dbl_pct" = "20%",
    "dataset" = cur_dataset,
    "precision" = precision,
    "recall" = recall
  )
  plot_df[[twenty_file]] <- cur_twenty_out
  
  # for forty dbl 
  # True Positives: Elements in both
  TP <- length(intersect(control_cc, forty_cc))

  # False Positives: Elements in predictions but not in ground truth
  FP <- length(setdiff(forty_cc, control_cc))  
  FN <- length(setdiff(control_cc, forty_cc)) 
  precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
  recall <- TP / (TP + FN )  # recall: TP out of all elements
  cur_forty_out <- list(
    "dbl_pct" = "40%",
    "dataset" = cur_dataset,
    "precision" = precision,
    "recall" = recall
  )
  plot_df[[forty_file]] <- cur_forty_out
}
plot_df <- data.table::rbindlist(plot_df)|>
  as.data.frame()
write.csv(plot_df,
          "/projects/p31666/zzhang/doublet-bchmk/plots/functional_analysis/cc.csv",
          quote = F,
          row.names = F)

# Reshape the data to long format
long_df <- plot_df %>%
  pivot_longer(cols = c(precision, recall), names_to = "metric", values_to = "value")

# Generate the plot
p <- ggplot(long_df, aes(x = dataset, y = value, group = dbl_pct, color = dbl_pct)) +
  geom_line() +
  facet_wrap(~metric, scales = "free_y") +
  scale_y_continuous(limits = c(0, 1)) +
  theme_minimal() +
  labs(title = "Precision and recall by Dataset",
       x = "Dataset",
       y = "Value",
       color = "Combination") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))

svg("/projects/p31666/zzhang/doublet-bchmk/plots/functional_analysis/cc.svg")
print(p)
dev.off()
```

