```{r}
library(ggplot2)
library(glue)
library(tidyverse)

```

```{r}
DE_root <- "/projects/p31666/zzhang/doublet-bchmk/data/DE_output"
```

```{r}
all_DEG_dirs <- list.dirs(DE_root, full.names = T, recursive = F)
plot_df <- list()

for(cur_deg_dir in all_DEG_dirs){
  all_deg_files <- list.files(cur_deg_dir, full.names = T)
  
  ten_files <- grep("ten", all_deg_files, value = TRUE)
  twenty_files <- grep("twenty", all_deg_files, value = TRUE)
  control_files <- grep("control", all_deg_files, value = TRUE)
  forty_files <- grep("forty", all_deg_files, value = TRUE)
  
  for(cur_control_file in control_files){
    cur_dataset <- basename(dirname(cur_control_file))
    cur_file_name <- basename(cur_control_file)
    test_method <- sub(".*__(.*)\\.csv.*", "\\1", cur_file_name)
    doublet_pct <- "0%"
    comp <- strsplit(cur_file_name, "__")[[1]][1]
    control_deg_df <- read.csv(cur_control_file)
    control_deg <- dplyr::filter(control_deg_df, (abs(avg_log2FC) > 0.585) & (p_val_adj<0.01))[["gene"]]
    control_non_deg <- dplyr::filter(control_deg_df, (abs(avg_log2FC) <= 0.585) | (p_val_adj>=0.01))[["gene"]]
    
    ten_DE_file <- grep(test_method, ten_files, value = TRUE)
    ten_deg_df <- read.csv(ten_DE_file)
    ten_deg <- dplyr::filter(ten_deg_df, (abs(avg_log2FC) > 0.585) & (p_val_adj<0.01))[["gene"]]
    ten_non_deg <- dplyr::filter(ten_deg_df, (abs(avg_log2FC) <= 0.585) | (p_val_adj>=0.01))[["gene"]]
    
    twenty_DE_file <- grep(test_method, twenty_files, value = TRUE)
    twenty_deg_df <- read.csv(twenty_DE_file)
    twenty_deg <- dplyr::filter(twenty_deg_df, (abs(avg_log2FC) > 0.585) & (p_val_adj<0.01))[["gene"]]
    twenty_non_deg <- dplyr::filter(twenty_deg_df, (abs(avg_log2FC) <= 0.585) | (p_val_adj>=0.01))[["gene"]]
    
    forty_DE_file <- grep(test_method, forty_files, value = TRUE)
    forty_deg_df <- read.csv(forty_DE_file)
    forty_deg <- dplyr::filter(forty_deg_df, (abs(avg_log2FC) > 0.585) & (p_val_adj<0.01))[["gene"]]
    forty_non_deg <- dplyr::filter(forty_deg_df, (abs(avg_log2FC) <= 0.585) | (p_val_adj>=0.01))[["gene"]]
    
    # for ten dbl 
    # True Positives: Elements in both
    TP <- length(intersect(control_deg, ten_deg))
    # True Negatives: Elements in both non deg
    TN <- length(intersect(control_non_deg, ten_non_deg))
    # False Positives: Elements in predictions but not in ground truth
    FP <- length(setdiff(ten_deg, control_deg))  
    FN <- length(setdiff(control_deg, ten_deg)) 
    precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
    recall <- TP / (TP + FN )  # recall: TP out of all elements
    TNR <- TN / (TN + FP)
    cur_ten_out <- list(
      "dbl_pct" = "10%",
      "dataset" = cur_dataset,
      "comp" = comp,
      "method" = test_method,
      "precision" = precision,
      "recall" = recall,
      "TNR" = TNR
    )
    plot_df[[ten_DE_file]] <- cur_ten_out
    
    # for twenty dbl 
    # True Positives: Elements in both
    TP <- length(intersect(control_deg, twenty_deg))
    TN <- length(intersect(control_non_deg, twenty_non_deg))
    # False Positives: Elements in predictions but not in ground truth
    FP <- length(setdiff(twenty_deg, control_deg))  
    FN <- length(setdiff(control_deg, twenty_deg)) 
    precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
    recall <- TP / (TP + FN)  # recall: TP out of all elements
    TNR <- TN / (TN + FP)
    cur_twenty_out <- list(
      "dbl_pct" = "20%",
      "dataset" = cur_dataset,
      "comp" = comp,
      "method" = test_method,
      "precision" = precision,
      "recall" = recall,
      "TNR" = TNR
    )
    plot_df[[twenty_DE_file]] <- cur_twenty_out
    
    # for forty dbl 
    # True Positives: Elements in both
    TP <- length(intersect(control_deg, forty_deg))
    TN <- length(intersect(control_non_deg, forty_non_deg))
    # False Positives: Elements in predictions but not in ground truth
    FP <- length(setdiff(forty_deg, control_deg))  
    FN <- length(setdiff(control_deg, forty_deg)) 
    precision <- TP / (TP + FP)  # Precision: TP out of all positive predictions
    recall <- TP / (TP + FN)  # recall: TP out of all elements
    TNR <- TN / (TN + FP)
    cur_forty_out <- list(
      "dbl_pct" = "40%",
      "dataset" = cur_dataset,
      "comp" = comp,
      "method" = test_method,
      "precision" = precision,
      "recall" = recall,
      "TNR" = TNR
    )
    plot_df[[forty_DE_file]] <- cur_forty_out
  }
}
plot_df <- data.table::rbindlist(plot_df)|>
  as.data.frame()
write.csv(plot_df,
          "/projects/p31666/zzhang/doublet-bchmk/plots/functional_analysis/de.csv",
          quote = F,
          row.names = F)

# Reshape the data to long format
long_df <- plot_df %>%
  pivot_longer(cols = c(precision, recall, TNR), names_to = "metric", values_to = "value")

# Generate the plot
p <- ggplot(long_df, aes(x = dataset, y = value, group = interaction(dbl_pct, method), color = interaction(dbl_pct, method))) +
  geom_line() +
  facet_wrap(~metric, scales = "free_y") +
  scale_y_continuous(limits = c(0, 1)) +
  theme_minimal() +
  labs(title = "Precision and recall by Dataset",
       x = "Dataset",
       y = "Value",
       color = "Combination") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))

svg("/projects/p31666/zzhang/doublet-bchmk/plots/functional_analysis/de.svg")
print(p)
dev.off()
```
```{r}
ground_truth <- c("a", "b", "c", "d")
predictions <- c("a", "e", "c", "f")

# Convert vectors to unique sets
ground_truth_set <- unique(ground_truth)
predictions_set <- unique(predictions)

# Calculate TP, FP, and FN
TP <- length(intersect(ground_truth_set, predictions_set))  # True Positives: Elements in both
FP <- (setdiff(predictions_set, ground_truth_set))   # False Positives: Elements in predictions but not in ground truth
FN <- (setdiff(ground_truth_set, predictions_set))  
```

