```{r}
require(Chord)
require(PRROC)
require(Matrix)
require(Seurat)
require(glue)
require(purrr)
require(data.table)
require(dplyr)
require(stringr)
```

```{r}
load_fatemap_into_seurat<-function(data_dir, doublets_pct=0.08){
  expression_matrix <- Read10X(data.dir = data_dir)
  seurat_object <- CreateSeuratObject(counts = expression_matrix)
  singlets_file <- glue("{data_dir}/singlets_all.txt")

  # key file for simulaitng doublets
  singlets_pair_for_doublet_simulation_file<-list.files(data_dir, pattern="corrected_singlet_pairs.csv")

  # extract the singlets
  singlets_pair_for_doublet_simulation_file<-glue("{data_dir}/{singlets_pair_for_doublet_simulation_file}")
  singlets<-read.delim(singlets_file,header = F, sep = "\n")[,1]|>
    as.vector()|>
    paste("-1",sep = "")

  # extract the singlet paris
  singlet_pair_df<-read.csv(singlets_pair_for_doublet_simulation_file, header = F)|>
    dplyr::mutate_each(funs = function(x) str_remove_all(x," "))
  # remove combinations that did not pass QC in seurat
  all_seurat_cells<-seurat_object@meta.data|>row.names()

  # take average of expression to produce doublets
  real_cells_pt1<-singlet_pair_df$V1
  real_cells_pt2<-singlet_pair_df$V2
  assay_for_simulated_doublets<-seurat_object@assays$RNA@counts[,c(real_cells_pt1, real_cells_pt2)]
  avg_assay_ori<-(assay_for_simulated_doublets[, real_cells_pt1] + assay_for_simulated_doublets[, real_cells_pt2])/2


 # create artificial doublet ID
  singlets_in_seurat <- singlets[singlets %in% colnames(seurat_object)]
  doublet_id<-paste(singlet_pair_df$V1,singlet_pair_df$V2, sep = "--")
  colnames(avg_assay_ori)<-doublet_id
  num_doublets<-round(length(singlets_in_seurat)*doublets_pct/(1+doublets_pct)) #derived from the case where 2 unique singlets make up 1 doublet, num_doublets = doublets_pct*(num_singlets-num_doublets)
  avg_assay <- avg_assay_ori[,1:num_doublets]
  doublet_object<-CreateSeuratObject(counts = avg_assay)


  singlets_used_for_doublets <- unique(unlist(strsplit(colnames(avg_assay), "--")))
  singlets_to_keep <- setdiff(colnames(seurat_object), singlets_used_for_doublets)
  singlets_to_keep_in_seurat <- intersect(singlets_in_seurat, singlets_to_keep)
  if (length(singlets_to_keep_in_seurat) > (num_doublets*(1-doublets_pct)/doublets_pct)) {
    singlets_trimmed <- sample(singlets_to_keep_in_seurat, num_doublets*(1-doublets_pct)/doublets_pct)
  } else {
    num_doublets <- round(length(singlets_in_seurat)*doublets_pct/(1-doublets_pct)) #calculate the number of doublets, no assumptions about removal being made
    avg_assay_new<-avg_assay_ori[,1:num_doublets]
    singlets_used_for_doublets <- unique(unlist(strsplit(colnames(avg_assay_new), "--")))
    singlets_to_keep <- setdiff(colnames(seurat_object), singlets_used_for_doublets)
    singlets_to_keep_in_seurat <- intersect(singlets_in_seurat, singlets_to_keep) # remove singlets used to make doublets
    num_doublets_adjusted <- round((length(singlets_to_keep_in_seurat)*doublets_pct) / (1-doublets_pct)) # adjust the number of doublets based on the number of singlets removed
    avg_assay_adjusted <- avg_assay_new[, 1:num_doublets_adjusted] # subset the avg_assay_new to be as long as the adjusted doublet count
    doublet_object <- CreateSeuratObject(counts = avg_assay_adjusted) #create doublet object
    singlets_trimmed <- singlets_to_keep_in_seurat #no more singlets removed after the ones used to make doublets are removed
  }
  singlet_object <- seurat_object[, singlets_trimmed]

  # tag doublet labels back to the doublet object
  label<-rep("doublet",ncol(doublet_object))|>
    as.data.frame()
  rownames(label)<-colnames(doublet_object)
  doublet_object<-AddMetaData(doublet_object, label, col.name = "label")

  # merge the two objects
  singlet_object<-seurat_object[, singlets_in_seurat]
  label<-rep("singlet",ncol(singlet_object))|>
    as.data.frame()
  rownames(label)<-colnames(singlet_object)
  singlet_object<-AddMetaData(singlet_object, label, col.name = "label")
  doublet.seurat<-merge(singlet_object, y = doublet_object, project = "combined_doublet_singlet")
  doublet.seurat
}

run_chord<-function(doublet.seurat, exp_dbl, temp_dir){
  doublets_pct_str <- as.character(round(exp_dbl, 2))
  temp_ <- glue("{temp_dir}/{doublets_pct_str}__{exp_dbl}")
  chord(seu=doublet.seurat,doubletrate = exp_dbl,overkill = T,outname = temp_)
  cur_res <- read.csv(glue("{temp_}real_score.csv"))
  cur_res[["label"]] <- sapply(cur_res$X, function(x){
    if(grepl("--", x)){
      out <- "doublet"
    }else{
      out <- "singlet"
    }
    out
  })
  fg <- cur_res[cur_res$label=="doublet",][["chord"]]
  bg <- cur_res[cur_res$label=="singlet",][["chord"]]
  if(var(fg)==0 | var(bg)==0){
    print("Chord failed due to all cells having identical scores")
    output <- list(
      "roc"="NA",
      "pr"="NA"
    )
  }else{
    pr <- pr.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
    cur_pr<-pr$auc.integral
    roc <- roc.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
    cur_roc<-roc$auc
    output<-list(
      "roc"=cur_roc,
      "pr"=cur_pr
    )
  }
}
run_bchmk<-function(data_dir, data_sample_ID, num_to_test, exp_dbl, act_dbl, temp_dir){
  df_ls<-NULL
  for(idx in 1:num_to_test){
    seurat_object<-load_fatemap_into_seurat(data_dir, doublets_pct=act_dbl)
    cur_res<-run_chord(seurat_object, exp_dbl, temp_dir=temp_dir)
    df_ls<-rbindlist(list(df_ls,cur_res))
  }
  all_stats<-data.frame(df_ls)
  all_stats<-cbind(ID=rep(data_sample_ID,nrow(all_stats)), all_stats)
  all_stats
}

run_chord_on_dataset<-function(data_dir, METHOD_ID, exp_dbl, actual_dbl, num_to_test=5){
  print(glue("Working on dataset: {data_dir}"))
  dir_10X <- glue("{data_dir}/10X")
  TEMP_root <- "D:/Workspace/Goyal_Lab/temp"
  dataset_id <- strsplit(data_dir,"/")[[1]][[length(strsplit(data_dir,"/")[[1]])]]
  sample_dirs<-list.dirs(path = dir_10X, full.names = TRUE, recursive = F)
  print(sample_dirs)
  stats <- list()
  out_df<-NULL
  for (cur_sample_dir in sample_dirs){
    # cur_seurat_object<-load_fatemap_into_seurat(cur_sample_dir, labels_, doublets_pct=actual_dbl)
    cur_sample_id<-strsplit(cur_sample_dir,"/")[[1]][[length(strsplit(cur_sample_dir,"/")[[1]])]]
    cur_data_sample_id<-glue("{dataset_id}_{cur_sample_id}")
    str_exp <- as.character(exp_dbl)
    str_act <- as.character(actual_dbl)
    cur_temp_dir <- glue("{TEMP_root}/exp_{str_exp}__act_{str_act}")
    dir.create(cur_temp_dir, showWarnings = TRUE, recursive = TRUE)
    cur_df <- run_bchmk(cur_sample_dir, cur_data_sample_id, num_to_test, exp_dbl = exp_dbl,
                        act_dbl = actual_dbl, temp_dir = cur_temp_dir)
    out_df<-rbindlist(list(out_df, cur_df))|>
      data.frame()
  }
  out_df
}
```



```{r include=FALSE}
data_dir <- "D:/Workspace/Goyal_Lab/data/FM01"
method_id <- "chord"
exp_dbl <- 0.05
actual_dbl <- 0.08
num_to_test <- 1
cur_df1 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.05, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df1$dbl_exp <- 0.05
cur_df1$dbl_act <- actual_dbl

cur_df2 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.08, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df2$dbl_exp <- 0.08
cur_df2$dbl_act <- actual_dbl

cur_df3 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.1, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df3$dbl_exp <- 0.1
cur_df3$dbl_act <- actual_dbl

cur_df4 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.15, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df4$dbl_exp <- 0.15
cur_df4$dbl_act <- actual_dbl

cur_df5 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.2, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df5$dbl_exp <- 0.2
cur_df5$dbl_act <- actual_dbl

cur_df6 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.25, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df6$dbl_exp <- 0.25
cur_df6$dbl_act <- actual_dbl

cur_out_df <- rbindlist(list(cur_df1, cur_df2, cur_df3, cur_df4, cur_df5, cur_df6))|>
  data.frame()

all_detection_rates_file<-glue("{data_dir}/all_detection_rates_{actual_dbl}.tsv")
write.table(cur_out_df, file = all_detection_rates_file, quote = FALSE, sep="\t",row.names = FALSE)

```

```{r}
data_dir <- "D:/Workspace/Goyal_Lab/data/FM02"
method_id <- "chord"
actual_dbl <- 0.08
num_to_test <- 1
cur_df1 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.05, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df1$dbl_exp <- 0.05
cur_df1$dbl_act <- actual_dbl

cur_df2 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.08, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df2$dbl_exp <- 0.08
cur_df2$dbl_act <- actual_dbl

cur_df3 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.1, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df3$dbl_exp <- 0.1
cur_df3$dbl_act <- actual_dbl

cur_df4 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.15, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df4$dbl_exp <- 0.15
cur_df4$dbl_act <- actual_dbl

cur_df5 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.2, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df5$dbl_exp <- 0.2
cur_df5$dbl_act <- actual_dbl

cur_df6 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.25, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df6$dbl_exp <- 0.25
cur_df6$dbl_act <- actual_dbl

cur_out_df <- rbindlist(list(cur_df1, cur_df2, cur_df3, cur_df4, cur_df5, cur_df6))|>
  data.frame()

all_detection_rates_file<-glue("{data_dir}/all_detection_rates_{actual_dbl}.tsv")
write.table(cur_out_df, file = all_detection_rates_file, quote = FALSE, sep="\t",row.names = FALSE)
```

```{r}
data_dir <- "D:/Workspace/Goyal_Lab/data/ClonMapper"
method_id <- "chord"
actual_dbl <- 0.08
num_to_test <- 1
cur_df1 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.05, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df1$dbl_exp <- 0.05
cur_df1$dbl_act <- actual_dbl

cur_df2 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.08, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df2$dbl_exp <- 0.08
cur_df2$dbl_act <- actual_dbl

cur_df3 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.1, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df3$dbl_exp <- 0.1
cur_df3$dbl_act <- actual_dbl

cur_df4 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.15, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df4$dbl_exp <- 0.15
cur_df4$dbl_act <- actual_dbl

cur_df5 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.2, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df5$dbl_exp <- 0.2
cur_df5$dbl_act <- actual_dbl

cur_df6 <- run_chord_on_dataset(data_dir, method_id, exp_dbl = 0.25, actual_dbl = actual_dbl, num_to_test = num_to_test)
cur_df6$dbl_exp <- 0.25
cur_df6$dbl_act <- actual_dbl

cur_out_df <- rbindlist(list(cur_df1, cur_df2, cur_df3, cur_df4, cur_df5, cur_df6))|>
  data.frame()

all_detection_rates_file<-glue("{data_dir}/all_detection_rates_{actual_dbl}.tsv")
write.table(cur_out_df, file = all_detection_rates_file, quote = FALSE, sep="\t",row.names = FALSE)
```





